sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  allow_failures:
    - env: ALLOW_FAIL=true
  include:
    - php: 7.4
      env:
        - CS_CHECK=true
        - ANALYSE=true
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 8.0
      env:
        - CS_CHECK=true
        - ANALYSE=true
    - php: 8.0
      env:
        - DEPS=lowest
    - php: 8.1
      env:
        - CS_CHECK=true
        - ANALYSE=true
        - ALLOW_FAIL=true
    - php: 8.1
      env:
        - DEPS=lowest
        - ALLOW_FAIL=true

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - composer show

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $ANALYSE == 'true' ]]; then composer analyse ; fi
